version: '3.8'

services:
  php-fpm:
    image: image-domain:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_gateauwala
    volumes:
      - ./gateauwala:/var/www/html
    networks:
      - docker-network-html

  nginx:
    image: nginx:latest
    container_name: nginx-gateauwala
    ports:
      - "${PORT}:80"
    volumes:
      - ./gateauwala:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - docker-network-html

networks:
  docker-network-html:
    driver: bridge